### ISSUE TITLE
Feedback Milestone 3

### ISSUE THREAD

**Issue by thasus** [UBC-MDS/Mental_Health_Issue_Tracker#22]
The interactive word cloud is looking so much better! Good job making it work. 

I wonder if its worthwhile trimming down the number of countries to display only ones that have relevant stats in the database (more than just a single data point). Otherwise the long list of countries is distracting

Your code is well documented and laid out.

**Comment by mchiriboga** [comment]
Thanks for the feedback @thasus. We implemented it, so now we're only showing the countries with more than 10 responses. This also fixes the wordcloud issue, since all countries now have at least two conditions to display. We had already created a release v4.0, so we marked it as prerelease and created a new one ([v4.1](https://github.com/UBC-MDS/Mental_Health_Issue_Tracker/releases/tag/v4.1)) which is our Milestone 4 release.
